- name: Create an instance
  hosts: localhost
  gather_facts: no
  connection: local

  vars_files:
    - vars/vars.yml

  tasks:
   - name: create a disk
     gcp_compute_disk:
         name: "{{ gcp_disk_name }}"
         size_gb: "{{ gcp_disk_size }}"
         source_image: "{{ gcp_source_image }}"
         zone: "{{ gcp_disk_zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: "{{ gcp_disk_state }}"
     register: disk

   - name: create a network
     gcp_compute_network:
      name: 'development'
      project: "development-network-238800"
      #project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: present
     register: network


   - name: create a subnetwork
     gcp_compute_subnetwork:
      name: us-east4-dev
      region: us-east4
      network: "{{ network }}"
      ip_cidr_range: 10.8.16.0/20
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
     register: subnetwork

   - name: create a instance
     gcp_compute_instance:
      name: "cloud-instance"
      machine_type: n1-standard-1
      zone: "{{ gcp_disk_zone }}"
      project: "{{ gcp_project }}"
      disks:
      - auto_delete: true
        boot: true
        source: "{{ disk }}"
      network_interfaces:
      - network: "{{ network }}"
      - subnetwork: "{{ subnetwork }}"
      state: present
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      metadata:
       istest: true
     register: gce
 
   - name: Save host data
     add_host:
       hostname: "{{ item.public_ip }}"
       groupname: gce_instances_ips
     with_items: "{{ gce.instance_data }}"

   - name: Wait for SSH for instances
     wait_for:
       delay: 1
       host: "{{ item.public_ip }}"
       port: 22
       state: started
       timeout: 30
     with_items: "{{ gce.instance_data }}"
