- name: create disk and report disk info
  hosts: localhost
  gather_facts: no
  connection: local

  vars_files:
    - vars/vars.yml

  tasks:
   - name: create a disk
     gcp_compute_disk:
         name: "{{ gcp_disk_name }}"
         size_gb: "{{ gcp_disk_size }}"
         source_image: "{{ gcp_source_image }}"
         zone: "{{ gcp_disk_zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: "{{ gcp_disk_state }}"
     register: disk_info

   - name: disk info
     debug:
         msg: "{{ disk_info }}"
     with_items: "{{ disk_info.name }}"
