- name: Create an instance
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:

   - name: create a service account
     gcp_iam_service_account:
       name: '"{{resource_name}}@{{gcp_project}}.google.com.iam.gserviceaccount.com"'
       display_name: My Ansible test key
       project: test_project
       auth_kind: serviceaccount
       service_account_file: "/tmp/auth.pem"
       state: present
